name: Build mirror

on:
  repository_dispatch:
    types: [build-mirror]

jobs:
  build:
    # build static mirror of oleng.github.io

    runs-on: ubuntu-latest
    env:
      repository: ${{ github.event.client_payload.repository }}
      remote_branch: ${{ github.event.client_payload.branch }}

    steps:

      - name: Checkout remote branch
        id: checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ env.repository }}
          remote_branch: ${{ env.remote_branch }}

      - name: Mirror
        id: integration
        run: |
          echo $PWD
          echo "${{ env.repository }}"
          ls -la
          git remote -v
          git add .
          git status

        # git push