name: Build mirror

on:
  repository_dispatch:
    types: [build-mirror]

jobs:
  build:
    # build static mirror of oleng.github.io

    runs-on: ubuntu-latest
    env:
      remote_repository: ${{ github.event.client_payload.repository }}
      remote_origin: ${{ github.event.client_payload.origin }}

    steps:

      - name: Checkout remote branch
        id: checkout
        uses: actions/checkout@v2
        with:
          remote_repository: ${{ env.repository }}
          remote_origin: ${{ env.remote_origin }}

      - name: Mirror
        id: integration
        run: |
          echo $PWD
          echo "${{ env.remote_repository }}"
          ls -la
          git remote -v
          git add .
          git status

        # git push